// data.jsx — All sample data for Alamut prototype
// Realistic Pakistani creators, brands, campaigns, messages

const CREATORS = [
  {
    id: "hira",
    handle: "hira.styles",
    name: "Hira Mansoor",
    avatar: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200&h=200&fit=crop",
    cover: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&h=400&fit=crop",
    city: "Lahore",
    bio: "Lifestyle & fashion stories from Lahore. Soft-launching small Pakistani brands since 2022.",
    categories: ["Fashion", "Lifestyle", "Beauty"],
    score: 86,
    priceTier: "$$",
    priceMin: 8000, priceMax: 35000,
    verified: true,
    channels: [
      { platform: "instagram", handle: "@hira.styles", followers: 18400, engagement: 4.8 },
      { platform: "tiktok", handle: "@hira.styles", followers: 22000, engagement: 6.2 },
    ],
    audience: { female: 78, male: 22, age2534: 42, age1824: 31, topCity: "Lahore" },
    rate: 25000,
    pastBrands: ["Sapphire", "Sana Safinaz", "Outfitters"],
  },
  {
    id: "bilal",
    handle: "bilalwrites",
    name: "Bilal Ahmed",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    cover: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=400&fit=crop",
    city: "Karachi",
    bio: "Writing for the new world of work. HR analytics, recruiter tools, mental health at work. 8K newsletter readers.",
    categories: ["B2B", "HR Tech", "Newsletter"],
    score: 92,
    priceTier: "$$$",
    priceMin: 80000, priceMax: 250000,
    verified: true,
    channels: [
      { platform: "linkedin", handle: "Bilal Ahmed", followers: 45200, engagement: 5.1 },
      { platform: "newsletter", handle: "Future of Work PK", followers: 8100, engagement: 38.0 },
    ],
    audience: { female: 41, male: 59, age2534: 51, age3544: 28, topCity: "Karachi" },
    rate: 145000,
    pastBrands: ["Bazaar Technologies", "PostEx", "Mathskills"],
  },
  {
    id: "zenith",
    handle: "zenith.travels",
    name: "Zenith Khan",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&h=200&fit=crop",
    cover: "https://images.unsplash.com/photo-1606117331085-5760e3b58520?w=1200&h=400&fit=crop",
    city: "Islamabad",
    bio: "Documenting Northern Pakistan. 500K subscribers, weekly drops. Hunza, Skardu, Fairy Meadows.",
    categories: ["Travel", "Outdoor", "Photography"],
    score: 95,
    priceTier: "$$$$",
    priceMin: 300000, priceMax: 850000,
    verified: true,
    channels: [
      { platform: "youtube", handle: "Zenith Travels", followers: 512000, engagement: 8.4 },
      { platform: "instagram", handle: "@zenith.travels", followers: 198000, engagement: 6.1 },
    ],
    audience: { female: 38, male: 62, age2534: 44, age1824: 26, topCity: "Lahore" },
    rate: 575000,
    pastBrands: ["PIA", "Daraz", "Samsung"],
  },
  {
    id: "mahnoor",
    handle: "mahnoor.eats",
    name: "Mahnoor Tariq",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
    cover: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1200&h=400&fit=crop",
    city: "Karachi",
    bio: "Karachi food scene, hidden dhabas, dessert obsessions. 4 reels a week.",
    categories: ["Food", "Karachi", "Lifestyle"],
    score: 81,
    priceTier: "$$",
    priceMin: 12000, priceMax: 45000,
    verified: true,
    channels: [
      { platform: "instagram", handle: "@mahnoor.eats", followers: 86000, engagement: 7.3 },
      { platform: "tiktok", handle: "@mahnooreats", followers: 124000, engagement: 9.1 },
    ],
    audience: { female: 64, male: 36, age2534: 39, age1824: 35, topCity: "Karachi" },
    rate: 32000,
    pastBrands: ["Foodpanda", "Cheetay", "Daraz"],
  },
  {
    id: "ahmer",
    handle: "ahmer.tech",
    name: "Ahmer Saleem",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&h=200&fit=crop",
    cover: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&h=400&fit=crop",
    city: "Islamabad",
    bio: "Tech reviews in Urdu and English. Phones, laptops, AI tools. PTA-approved unboxings.",
    categories: ["Tech", "Reviews", "Gadgets"],
    score: 78,
    priceTier: "$$$",
    priceMin: 60000, priceMax: 180000,
    verified: true,
    channels: [
      { platform: "youtube", handle: "Ahmer Tech", followers: 215000, engagement: 5.8 },
      { platform: "x", handle: "@ahmer_tech", followers: 32000, engagement: 3.2 },
    ],
    audience: { female: 18, male: 82, age2534: 38, age1824: 41, topCity: "Karachi" },
    rate: 110000,
    pastBrands: ["Infinix", "Samsung Pakistan", "Daraz"],
  },
  {
    id: "anum",
    handle: "anum.parents",
    name: "Anum Chaudhry",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop",
    cover: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=1200&h=400&fit=crop",
    city: "Lahore",
    bio: "Parenting honest. Two kids, no filter. Reviews kid products, schools, and Pakistani parenting culture.",
    categories: ["Parenting", "Family", "Kids"],
    score: 84,
    priceTier: "$$",
    priceMin: 18000, priceMax: 65000,
    verified: false,
    channels: [
      { platform: "instagram", handle: "@anum.parents", followers: 54000, engagement: 6.4 },
      { platform: "youtube", handle: "Anum & Co.", followers: 28000, engagement: 4.2 },
    ],
    audience: { female: 89, male: 11, age2534: 48, age3544: 34, topCity: "Lahore" },
    rate: 42000,
    pastBrands: ["Pampers", "Servis", "Englishbiz"],
  },
  {
    id: "fahad",
    handle: "fahad.fitness",
    name: "Fahad Iqbal",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
    cover: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&h=400&fit=crop",
    city: "Karachi",
    bio: "Strength coach. Pakistan-first nutrition. Daily reels, weekly deep-dives on YouTube.",
    categories: ["Fitness", "Nutrition", "Health"],
    score: 79,
    priceTier: "$$",
    priceMin: 22000, priceMax: 75000,
    verified: true,
    channels: [
      { platform: "instagram", handle: "@fahad.fitness", followers: 92000, engagement: 5.6 },
      { platform: "tiktok", handle: "@fahadfit", followers: 67000, engagement: 7.8 },
    ],
    audience: { female: 28, male: 72, age2534: 46, age1824: 29, topCity: "Karachi" },
    rate: 48000,
    pastBrands: ["MyProtein", "Ufone", "Optimum Nutrition"],
  },
  {
    id: "saadia",
    handle: "saadia.finance",
    name: "Saadia Rehman",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop",
    cover: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&h=400&fit=crop",
    city: "Karachi",
    bio: "Personal finance for young Pakistanis. Mutual funds, taxes, salary negotiation. Demystifying money.",
    categories: ["Finance", "B2B", "Education"],
    score: 88,
    priceTier: "$$$",
    priceMin: 90000, priceMax: 220000,
    verified: true,
    channels: [
      { platform: "linkedin", handle: "Saadia Rehman", followers: 38000, engagement: 6.8 },
      { platform: "instagram", handle: "@saadia.finance", followers: 71000, engagement: 5.4 },
    ],
    audience: { female: 44, male: 56, age2534: 54, age3544: 22, topCity: "Karachi" },
    rate: 135000,
    pastBrands: ["Meezan Bank", "JazzCash", "PostEx"],
  },
];

const CAMPAIGNS = [
  {
    id: "c1",
    name: "Eid Edit '26 — Sapphire",
    brand: "Sapphire",
    status: "Live",
    budget: 1850000,
    spent: 1240000,
    confirmed: 8,
    live: 5,
    submitted: 3,
    paid: 920000,
    creators: ["hira", "mahnoor", "anum", "saadia"],
    placement: "Instagram Reel + Stories",
    deadline: "2026-05-22",
    brief: "Showcase the Eid '26 lawn collection in real-life styling. Authentic, candid, daily-wear angles. Brand-safe, no flashy edits.",
  },
  {
    id: "c2",
    name: "PostEx LinkedIn Thought-Leadership",
    brand: "PostEx",
    status: "Active",
    budget: 580000,
    spent: 145000,
    confirmed: 3,
    live: 0,
    submitted: 0,
    paid: 0,
    creators: ["bilal", "saadia"],
    placement: "LinkedIn Post + Newsletter Mention",
    deadline: "2026-06-10",
    brief: "Position PostEx as the go-to logistics partner for D2C brands in Pakistan. Founder voice, data-led.",
  },
  {
    id: "c3",
    name: "Hunza Travel Series — PIA",
    brand: "PIA",
    status: "Planned",
    budget: 4200000,
    spent: 0,
    confirmed: 0,
    live: 0,
    submitted: 0,
    paid: 0,
    creators: ["zenith"],
    placement: "YouTube Long-form (3 episodes)",
    deadline: "2026-07-15",
    brief: "Three-episode Northern Pakistan travel series featuring PIA domestic routes. Cinematic, story-led.",
  },
  {
    id: "c4",
    name: "Daraz Mobile Week",
    brand: "Daraz",
    status: "Completed",
    budget: 1200000,
    spent: 1180000,
    confirmed: 12,
    live: 12,
    submitted: 12,
    paid: 1180000,
    creators: ["ahmer", "fahad", "mahnoor"],
    placement: "Multi-platform burst",
    deadline: "2026-04-08",
    brief: "Drive purchase intent for Mobile Week sale. Honest unboxings + lifestyle integrations.",
  },
];

const CONVERSATIONS = [
  {
    id: "conv1",
    creatorId: "hira",
    campaignId: "c1",
    unread: 2,
    lastAt: "2 min ago",
    preview: "Got it — I can have the first reel ready by Thursday. Should I share the script first?",
    messages: [
      { from: "brand", text: "Hi Hira! Loved your last Sana Safinaz collab. We'd love you for our Eid '26 push.", time: "Yesterday, 3:42 PM" },
      { from: "creator", text: "Thank you! Sapphire is on my dream list — totally interested. What are we thinking?", time: "Yesterday, 4:18 PM" },
      { from: "brand", text: "1 Reel + 3 Stories featuring 2 outfits from the new collection. PKR 35K, plus product gifting.", time: "Yesterday, 4:22 PM" },
      { from: "creator", text: "Works for me. When do you need it live?", time: "Yesterday, 4:30 PM" },
      { from: "brand", text: "Ideally May 18th. Brief + samples will arrive Monday.", time: "Today, 10:14 AM" },
      { from: "creator", text: "Got it — I can have the first reel ready by Thursday. Should I share the script first?", time: "Today, 10:16 AM" },
    ],
  },
  {
    id: "conv2",
    creatorId: "bilal",
    campaignId: "c2",
    unread: 0,
    lastAt: "4 hours ago",
    preview: "Perfect, sending the draft post tomorrow morning ✓",
    messages: [
      { from: "brand", text: "Bilal — we read your piece on hidden HR costs at SMBs. PostEx's onboarding tool fits perfectly.", time: "Mon, 11:00 AM" },
      { from: "creator", text: "Appreciate it. Send me the deck — I'll pull a thread together if the data holds up.", time: "Mon, 11:42 AM" },
      { from: "brand", text: "Deck attached. PKR 145K for 1 LinkedIn post + 1 newsletter mention.", time: "Mon, 1:15 PM" },
      { from: "creator", text: "Numbers check out. I'm in. Will draft this week.", time: "Tue, 9:30 AM" },
      { from: "creator", text: "Perfect, sending the draft post tomorrow morning ✓", time: "4 hours ago" },
    ],
  },
  {
    id: "conv3",
    creatorId: "mahnoor",
    campaignId: "c1",
    unread: 1,
    lastAt: "Yesterday",
    preview: "Can the brief include vegetarian options? My audience asks a lot.",
    messages: [
      { from: "brand", text: "Hey Mahnoor! Eid food + Sapphire styling content opportunity. Interested?", time: "Wed, 2:00 PM" },
      { from: "creator", text: "Can the brief include vegetarian options? My audience asks a lot.", time: "Yesterday" },
    ],
  },
  {
    id: "conv4",
    creatorId: "zenith",
    campaignId: "c3",
    unread: 0,
    lastAt: "2 days ago",
    preview: "Locations locked: Hunza, Skardu, Fairy Meadows. Sending the shot list.",
    messages: [
      { from: "brand", text: "Zenith — PIA wants 3 episodes for the Northern series. PKR 25 lakh per episode.", time: "Last week" },
      { from: "creator", text: "Locations locked: Hunza, Skardu, Fairy Meadows. Sending the shot list.", time: "2 days ago" },
    ],
  },
  {
    id: "conv5",
    creatorId: "saadia",
    campaignId: "c2",
    unread: 0,
    lastAt: "5 days ago",
    preview: "Approved — let's go live next Tuesday.",
    messages: [
      { from: "brand", text: "Saadia, ready when you are.", time: "Last week" },
      { from: "creator", text: "Approved — let's go live next Tuesday.", time: "5 days ago" },
    ],
  },
];

const WALLET = {
  available: 2840000,
  reserved: 1620000,
  inFlight: 145000,
  currency: "PKR",
  ledger: [
    { date: "May 6", desc: "Top-up via JazzCash", amount: +500000, type: "topup", status: "Settled" },
    { date: "May 5", desc: "Released to Hira Mansoor — Eid Edit '26", amount: -33250, type: "release", status: "Settled" },
    { date: "May 5", desc: "Platform fee (10%)", amount: -3500, type: "fee", status: "Settled" },
    { date: "May 5", desc: "FBR WHT (5%)", amount: -1750, type: "tax", status: "Settled" },
    { date: "May 3", desc: "Reserved — Bilal Ahmed (PostEx campaign)", amount: -145000, type: "reserve", status: "In escrow" },
    { date: "May 2", desc: "Top-up via Raast", amount: +1500000, type: "topup", status: "Settled" },
    { date: "Apr 28", desc: "Released to Mahnoor Tariq", amount: -38400, type: "release", status: "Settled" },
    { date: "Apr 24", desc: "Top-up via JazzCash", amount: +800000, type: "topup", status: "Settled" },
  ],
};

const CREATOR_WALLET = {
  available: 187500,
  pending: 78000,
  lifetime: 2940000,
  currency: "PKR",
  ledger: [
    { date: "May 5", desc: "Sapphire — Eid Edit '26 (1 reel)", amount: +33250, gross: 35000, fee: -1750, status: "Paid" },
    { date: "Apr 28", desc: "Foodpanda — Iftar collab", amount: +28500, gross: 30000, fee: -1500, status: "Paid" },
    { date: "Apr 22", desc: "Cheetay — Promo reel", amount: +19000, gross: 20000, fee: -1000, status: "Paid" },
    { date: "Apr 15", desc: "Daraz — Mobile Week", amount: +106750, gross: 115000, fee: -8250, status: "Paid" },
    { date: "Apr 8", desc: "Withdraw to JazzCash *4291", amount: -150000, status: "Withdrawn" },
  ],
};

const SPARK_HISTORY = [
  { id: "s1", title: "30 LinkedIn HR creators · $5K", date: "Today" },
  { id: "s2", title: "Eid '26 fashion micro-influencers", date: "Yesterday" },
  { id: "s3", title: "Karachi food creators under 100K", date: "May 3" },
  { id: "s4", title: "B2B fintech newsletter sponsors", date: "Apr 29" },
];

// ─── PIPELINE STAGES ────────────────────────────────────────
// Invited → Pitched → Negotiating → Confirmed → In Progress → Submitted → Approved → Live → Paid
const PIPELINE_STAGES = [
  { id: "invited", label: "Invited", color: "var(--ink-3)" },
  { id: "pitched", label: "Pitched", color: "var(--info)" },
  { id: "negotiating", label: "Negotiating", color: "var(--gold)" },
  { id: "confirmed", label: "Confirmed", color: "var(--accent)" },
  { id: "submitted", label: "Submitted", color: "#8B5CF6" },
  { id: "approved", label: "Approved", color: "var(--moss)" },
  { id: "live", label: "Live", color: "var(--moss)" },
  { id: "paid", label: "Paid", color: "var(--ink)" },
];

// Deliverables and applicants per campaign (keyed by campaign id)
const COLLABS = [
  // Sapphire Eid '26
  { id: "x1", campaignId: "c1", creatorId: "hira", stage: "submitted", price: 35000, deadline: "May 18", appliedAt: "Apr 28", pitch: "I love Sapphire's lawn — happy to do a 'getting ready for Eid' POV reel that fits naturally with my morning content style.",
    deliverables: [
      { id: "d1", label: "Instagram Reel · 60s", status: "in_review", due: "May 18", submittedAt: "today, 11:14am",
        thumb: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&h=600&fit=crop",
        notes: "First cut attached. Open to revisions on the styling shots." },
      { id: "d2", label: "Stories ×3", status: "pending", due: "May 19" },
    ] },
  { id: "x2", campaignId: "c1", creatorId: "mahnoor", stage: "negotiating", price: 32000, deadline: "May 20", appliedAt: "May 1", pitch: "Could combine with my Iftar food content — Sapphire styling + my dessert recipes?",
    deliverables: [
      { id: "d3", label: "Instagram Reel · 90s", status: "pending", due: "May 20" },
    ] },
  { id: "x3", campaignId: "c1", creatorId: "anum", stage: "confirmed", price: 42000, deadline: "May 19", appliedAt: "Apr 30", pitch: "Eid morning routine with my kids in matching Sapphire — would love this.",
    deliverables: [
      { id: "d4", label: "Instagram Reel · 60s", status: "pending", due: "May 19" },
      { id: "d5", label: "Stories ×3", status: "pending", due: "May 19" },
    ] },
  { id: "x4", campaignId: "c1", creatorId: "saadia", stage: "approved", price: 28000, deadline: "May 16", appliedAt: "Apr 26", pitch: "Practical 'Eid budgeting' angle with Sapphire as the splurge — different from typical fashion creators.",
    deliverables: [
      { id: "d6", label: "Instagram Reel · 60s", status: "approved", due: "May 16", submittedAt: "May 14",
        thumb: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=600&fit=crop",
        approvedAt: "May 15" },
    ] },
  { id: "x5", campaignId: "c1", creatorId: "fahad", stage: "invited", price: 0, deadline: "—", appliedAt: "—",
    deliverables: [] },
  { id: "x6", campaignId: "c1", creatorId: "ahmer", stage: "pitched", price: 110000, deadline: "—", appliedAt: "May 4", pitch: "Tech angle: 'styling apps for Eid' — could feature Sapphire's website UX. Different lens.",
    deliverables: [] },
  // PostEx LinkedIn
  { id: "x7", campaignId: "c2", creatorId: "bilal", stage: "live", price: 145000, deadline: "May 28", appliedAt: "Apr 22", pitch: "",
    deliverables: [
      { id: "d7", label: "LinkedIn Post · 1500 words", status: "live", due: "May 25", submittedAt: "May 22",
        approvedAt: "May 24", liveAt: "May 25",
        permalink: "linkedin.com/posts/bilal-ahmed-postex" },
      { id: "d8", label: "Newsletter feature", status: "approved", due: "May 28" },
    ] },
  { id: "x8", campaignId: "c2", creatorId: "saadia", stage: "confirmed", price: 135000, deadline: "Jun 5", appliedAt: "Apr 28", pitch: "",
    deliverables: [
      { id: "d9", label: "LinkedIn Post", status: "pending", due: "Jun 5" },
    ] },
];

// Open campaigns the creator can apply to (from creator side)
const BRIEFS = [
  { id: "b1", campaignId: "c1", visible: true, matchScore: 94 },
  { id: "b2", campaignId: "c2", visible: true, matchScore: 62 },
  { id: "b3", campaignId: "c3", visible: false, matchScore: 38 }, // niche
];

// Activity feed (per campaign)
const CAMPAIGN_ACTIVITY = {
  c1: [
    { who: "Hira Mansoor", what: "submitted Reel for review", when: "2h ago", type: "submit" },
    { who: "Spark", what: "auto-suggested 4 more creators matching brief", when: "5h ago", type: "ai" },
    { who: "System", what: "released Rs 26,600 to Saadia (net of fees + WHT)", when: "Yesterday", type: "payment" },
    { who: "Sara", what: "approved Saadia's Reel", when: "Yesterday", type: "approval" },
    { who: "Anum Chaudhry", what: "accepted the brief", when: "May 12", type: "stage" },
    { who: "Mahnoor Tariq", what: "asked for revision in scope", when: "May 11", type: "message" },
  ],
};

// Performance analytics per campaign
const CAMPAIGN_PERF = {
  c1: {
    impressions: 248_400, reach: 192_100, engagement: 28_640,
    er: 11.5, cpm: 5_140, cpe: 43,
    saves: 4280, shares: 1840, profileVisits: 9120,
    weeklySeries: [12, 18, 14, 22, 28, 31, 38],
  },
  c2: {
    impressions: 38_200, reach: 28_400, engagement: 4_120,
    er: 10.8, cpm: 7_580, cpe: 70,
    saves: 612, shares: 488, profileVisits: 1140,
    weeklySeries: [4, 8, 11, 14, 18, 19, 22],
  },
};

window.ALAMUT_DATA = { CREATORS, CAMPAIGNS, CONVERSATIONS, WALLET, CREATOR_WALLET, SPARK_HISTORY,
  PIPELINE_STAGES, COLLABS, BRIEFS, CAMPAIGN_ACTIVITY, CAMPAIGN_PERF };
