// Invoice generator — opens a printable HTML invoice in a new window.
// User can save as PDF via the browser's print dialog. No external deps.

import type { Brand, Campaign, Creator, Transaction } from '@/lib/api/types';

interface InvoiceInput {
  transaction: Transaction;
  creator: Creator;
  brand: Brand | undefined;
  campaign: Campaign | undefined;
}

export function openInvoice({ transaction, creator, brand, campaign }: InvoiceInput) {
  const number = `INV-${transaction.id.replace(/[^a-z0-9]/gi, '').slice(-8).toUpperCase()}`;
  const date = new Date(transaction.at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  const amount = `$${Math.abs(transaction.amount).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${number} · ${creator.name}</title>
<style>
  @page { margin: 0.5in; }
  * { box-sizing: border-box; }
  body { font-family: 'Inter', system-ui, -apple-system, sans-serif; color: #1a1a1f; margin: 0; padding: 56px 64px; line-height: 1.55; }
  h1 { font-family: 'Fraunces', Georgia, serif; font-weight: 400; font-size: 56px; letter-spacing: -0.025em; margin: 0 0 8px; }
  .meta { font-family: ui-monospace, Menlo, monospace; font-size: 11px; letter-spacing: 0.10em; text-transform: uppercase; color: #666; }
  .row { display: grid; grid-template-columns: 1fr 1fr; gap: 32px; margin: 40px 0; }
  .block { border-top: 1px solid #ddd; padding-top: 14px; }
  .block .label { font-family: ui-monospace, Menlo, monospace; font-size: 10px; letter-spacing: 0.12em; text-transform: uppercase; color: #888; margin-bottom: 8px; }
  .block .value { font-size: 14px; line-height: 1.5; }
  table { width: 100%; border-collapse: collapse; margin: 32px 0; }
  th { font-family: ui-monospace, Menlo, monospace; font-size: 10px; letter-spacing: 0.12em; text-transform: uppercase; color: #888; text-align: left; padding: 12px 0; border-bottom: 1px solid #1a1a1f; font-weight: 500; }
  td { padding: 14px 0; border-bottom: 1px solid #eee; font-size: 14px; }
  td.amount { text-align: right; font-family: ui-monospace, Menlo, monospace; }
  .total { display: flex; justify-content: flex-end; margin-top: 16px; gap: 64px; }
  .total .lbl { font-family: ui-monospace, Menlo, monospace; font-size: 11px; letter-spacing: 0.10em; text-transform: uppercase; color: #666; align-self: end; padding-bottom: 6px; }
  .total .amt { font-family: 'Fraunces', Georgia, serif; font-size: 40px; letter-spacing: -0.02em; font-weight: 500; }
  .footer { margin-top: 64px; padding-top: 24px; border-top: 1px solid #ddd; font-size: 12px; color: #888; line-height: 1.5; }
  .actions { position: fixed; top: 16px; right: 16px; display: flex; gap: 8px; }
  .actions button { font-family: ui-monospace, Menlo, monospace; font-size: 11px; letter-spacing: 0.10em; text-transform: uppercase; padding: 10px 16px; border: 1px solid #1a1a1f; background: #1a1a1f; color: white; cursor: pointer; border-radius: 4px; }
  .actions button.alt { background: white; color: #1a1a1f; }
  @media print { .actions { display: none; } body { padding: 0; } }
</style>
</head>
<body>
  <div class="actions">
    <button onclick="window.print()">Print / Save as PDF</button>
    <button class="alt" onclick="window.close()">Close</button>
  </div>

  <div class="meta">Invoice · ${number}</div>
  <h1>${creator.name}</h1>
  <div class="meta">Issued ${date}</div>

  <div class="row">
    <div class="block">
      <div class="label">Bill from</div>
      <div class="value">
        <strong>${creator.name}</strong><br/>
        ${creator.handle}<br/>
        ${creator.city}, ${creator.country}<br/>
        ${creator.payout.method ? `${creator.payout.method} · ${creator.payout.account}` : ''}
      </div>
    </div>
    <div class="block">
      <div class="label">Bill to</div>
      <div class="value">
        <strong>${brand?.name || 'Brand'}</strong><br/>
        ${brand?.industry || ''}<br/>
        ${brand?.hq || ''}<br/>
        ${brand?.website || ''}
      </div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th style="width: 60%;">Description</th>
        <th>Reference</th>
        <th class="amount">Amount</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <strong>${campaign?.title || 'Campaign'}</strong><br/>
          <span style="color: #888; font-size: 13px;">${transaction.note}</span>
        </td>
        <td style="font-family: ui-monospace, Menlo, monospace; font-size: 12px; color: #888;">${campaign?.id || transaction.id}</td>
        <td class="amount">${amount}</td>
      </tr>
    </tbody>
  </table>

  <div class="total">
    <span class="lbl">Total · ${creator.payout.currency}</span>
    <span class="amt">${amount}</span>
  </div>

  <div class="footer">
    Generated by Alamut on ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}.
    Demo invoice — for real billing in production this would include tax IDs, VAT/GST as applicable, and platform-fee disclosure.
  </div>
</body>
</html>`;

  const w = window.open('', '_blank', 'width=900,height=1100');
  if (!w) {
    // Fall back to inline blob so the user still gets the invoice even with popups blocked.
    import('./toast').then(({ pushToast }) => {
      pushToast('Popups blocked — opening invoice in current tab instead', 'default');
    });
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    window.location.href = url;
    return;
  }
  w.document.open();
  w.document.write(html);
  w.document.close();
}
