// Campaigns — shared surface. Public case-study directory + detail view.

const CAMPAIGNS = [
  {
    id: 'camp-01',
    brand: 'Khaadi',
    title: 'Monsoon soft-launch',
    year: 2026,
    status: 'Live',
    city: 'Lahore',
    discipline: 'Fashion',
    cover: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1400&h=900&fit=crop',
    brief: 'Introduce the monsoon capsule to a younger audience in Lahore and Karachi without the usual TVC treatment. Documentary-style across 3 creators.',
    budget: '$14,000',
    window: 'Jun 15 – Jul 06, 2026',
    deliverables: ['6 Reels', '3 feed sets', '1 long-form', 'newsletter feature'],
    creators: ['c01', 'c03', 'c04'],
    results: [
      { k: 'Reach', v: '2.4M' },
      { k: 'Engagement', v: '7.2%' },
      { k: 'Saves', v: '18.4K' },
      { k: 'DMs to brand', v: '+640%' },
    ],
    milestones: [
      { d: 'Jun 02', t: 'Brief approved', done: true },
      { d: 'Jun 10', t: 'Creative round 1', done: true },
      { d: 'Jun 18', t: 'Shoot day', done: true },
      { d: 'Jun 22', t: 'First assets live', done: false, current: true },
      { d: 'Jul 06', t: 'Campaign wrap', done: false },
    ],
  },
  {
    id: 'camp-02',
    brand: 'Habibi Coffee Roasters',
    title: 'Eid 2026 gift box',
    year: 2026,
    status: 'Live',
    city: 'Karachi',
    discipline: 'Food',
    cover: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1400&h=900&fit=crop',
    brief: 'Launch the Eid gift box to tastemakers in Karachi and Dubai. Warm, slow storytelling — no discount codes, no urgency plays.',
    budget: '$6,200',
    window: 'Apr 20 – May 14, 2026',
    deliverables: ['3 Reels', '2 feed posts', '8 stories'],
    creators: ['c02', 'c06'],
    results: [
      { k: 'Reach', v: '840K' },
      { k: 'Engagement', v: '6.1%' },
      { k: 'Gift-box orders', v: '+312' },
      { k: 'Waitlist', v: '1,240' },
    ],
    milestones: [
      { d: 'Apr 02', t: 'Brief approved', done: true },
      { d: 'Apr 12', t: 'Creative round 1', done: true },
      { d: 'Apr 24', t: 'First assets live', done: true, current: true },
      { d: 'May 14', t: 'Campaign wrap', done: false },
    ],
  },
  {
    id: 'camp-03',
    brand: 'Generation Apparel',
    title: 'Heritage capsule — Lahore edit',
    year: 2026,
    status: 'In production',
    city: 'Lahore',
    discipline: 'Fashion',
    cover: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=1400&h=900&fit=crop',
    brief: 'A 4-minute documentary on the embroidery artisans behind the capsule. Cross-post across two creators and the brand channel.',
    budget: '$22,500',
    window: 'May 01 – Aug 10, 2026',
    deliverables: ['1 mini-doc', '2 Reel cut-downs', 'photo essay'],
    creators: ['c02', 'c06'],
    results: [],
    milestones: [
      { d: 'May 06', t: 'Brief approved', done: true },
      { d: 'Jun 02', t: 'Location scout', done: true },
      { d: 'Jul 18', t: 'Shoot week', done: false, current: true },
      { d: 'Aug 10', t: 'Premiere', done: false },
    ],
  },
  {
    id: 'camp-04',
    brand: 'Daraz',
    title: 'Home & Living, 90-day',
    year: 2025,
    status: 'Completed',
    city: 'Karachi',
    discipline: 'Interiors',
    cover: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=1400&h=900&fit=crop',
    brief: 'Establish Daraz as a credible destination for furniture and home. Long-form content, high production value.',
    budget: '$38,000',
    window: 'Sep 2025 – Dec 2025',
    deliverables: ['12 Reels', '6 long-form', 'blog series'],
    creators: ['c06', 'c04'],
    results: [
      { k: 'Reach', v: '5.1M' },
      { k: 'Furniture GMV', v: '+41%' },
      { k: 'Category CAC', v: '−28%' },
      { k: 'Repeat buyers', v: '+19%' },
    ],
    milestones: [
      { d: 'Sep 01', t: 'Brief approved', done: true },
      { d: 'Oct 15', t: 'Phase 1 live', done: true },
      { d: 'Nov 20', t: 'Phase 2 live', done: true },
      { d: 'Dec 15', t: 'Final report', done: true },
    ],
  },
  {
    id: 'camp-05',
    brand: 'Tapal Tea',
    title: 'Breakfast Table series',
    year: 2025,
    status: 'Completed',
    city: 'Lahore',
    discipline: 'Food',
    cover: 'https://images.unsplash.com/photo-1447078806655-40579c2520d6?w=1400&h=900&fit=crop',
    brief: 'A six-part breakfast table series across Pakistani cities. Cultural and intimate — no product shots.',
    budget: '$19,500',
    window: 'Mar 2025 – Jul 2025',
    deliverables: ['6 Reels', '6 feed sets', '2 podcast episodes'],
    creators: ['c03'],
    results: [
      { k: 'Reach', v: '3.2M' },
      { k: 'Brand recall', v: '+22pts' },
      { k: 'Unprompted mentions', v: '+4.1×' },
    ],
    milestones: [
      { d: 'Mar 01', t: 'Brief approved', done: true },
      { d: 'Apr 10', t: 'Ep 1 live', done: true },
      { d: 'Jul 05', t: 'Series wrap', done: true },
    ],
  },
  {
    id: 'camp-06',
    brand: 'Foree Shoes',
    title: 'Back-to-campus capsule',
    year: 2026,
    status: 'Open for applications',
    city: 'Islamabad',
    discipline: 'Fashion',
    cover: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1400&h=900&fit=crop',
    brief: 'Bring the back-to-campus capsule to university students. Looking for 4 creators with university-age followings.',
    budget: '$8,400',
    window: 'Aug 10 – Sep 15, 2026',
    deliverables: ['4 Reels', '4 feed posts', 'story sets'],
    creators: [],
    results: [],
    milestones: [
      { d: 'Jul 20', t: 'Applications open', done: true, current: true },
      { d: 'Jul 30', t: 'Creators selected', done: false },
      { d: 'Aug 10', t: 'Campaign start', done: false },
    ],
  },
];

const CAMPAIGN_DISCIPLINES = ['All', 'Fashion', 'Food', 'Interiors', 'Film', 'Design'];
const CAMPAIGN_STATUSES = ['All', 'Live', 'In production', 'Open for applications', 'Completed'];

Object.assign(window, { CAMPAIGNS, CAMPAIGN_DISCIPLINES, CAMPAIGN_STATUSES });
